language: python
cache: pip
dist: xenial
python:
   - "3.6"
   - "3.7"
   - "3.8"
env:
  matrix:
    - PANDAS_VERSION=0.23.4  && NUMPY_VERSION=1.19.0
    - PANDAS_VERSION=0.25.3  && NUMPY_VERSION=1.19.0
    - NUMPY_VERSION=1.15.4   && PANDAS_VERSION=1.1.0
    - NUMPY_VERSION=1.19.0   && PANDAS_VERSION=1.1.0
before_install:
  - ls
  # - sudo apt-get update
install: "make"
script:
  # command to run tests
  - make test
after_success:
  - coveralls
# Don't want notifications
notifications:
  email: false
