language: python
dist: trusty
python:
   - "2.7"
   - "3.4"
   - "3.5"
   - "3.6"
# Enable newer 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - sudo apt-get update
install:
  - "pip install -r dev-requirements.txt"
  - "pip install python-coveralls 'coverage>=4.4' pytest-cov seaborn"
# command to run tests
script:
  - py.test -s --cov=lifelines -vv --block=False --cov-report term-missing
  # enforce flake8 standards
  - flake8 lifelines --statistics --config=setup.cfg
after_success:
  coveralls
# Don't want notifications
notifications:
  email: false
